### ISSUE TITLE
CQ Inactive sends on two radios

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#129]
Active radio continues to send when CQ Inactive is initiated.
This places the SO2R station in multi category.

**Comment by n4af** [comment]
ALT-D is Ok.

**Comment by n4af** [comment]
Wkey works ok.

**Comment by ny4i** [comment]
I think I have this working. Can you share the scenarios that caused it to do this? 

I was sending CQ on active and now when I send CW on inactive,the active radio stops right away.

**Comment by ny4i** [comment]
Howie, The Pull request I created seems to get closer to this. Please let me know if this works properly.

**Comment by n4af** [comment]
Hi Tom -

To the best of my knowledge this was fixed some time ago.

CQ on active rig and then press CQ Inactive key. The main cq should stop
immediately.

73, Howie

http://n4af.net

**Comment by n4af** [comment]
ok, my mistake. I did recently open this, but fixed it pretty quickly in the latest 4.46.13

**Comment by ny4i** [comment]
I worked it because I could press CQ inactive and CW active and they both
were sending.

It works now.

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Mar 3, 2016, at 5:58 AM, Howie Hoyt <notifications@github.com> wrote:

Hi Tom -

To the best of my knowledge this was fixed some time ago.

CQ on active rig and then press CQ Inactive key. The main cq should stop
immediately.

73, Howie

http://n4af.net

On Wed, Mar 2, 2016 at 11:07 PM, Tom Schaefer <notifications@github.com>
wrote:

> I think I have this working. Can you share the scenarios that caused it to
> do this?
>
> I was sending CQ on active and now when I send CW on inactive,the active
> radio stops right away.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n4af/TR4W/issues/129#issuecomment-191572167>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/issues/129#issuecomment-191706742>.

**Comment by n4af** [comment]
ok. seems fine. it is up as 4.46.14

You were up late ?

73, Howie

http://n4af.net

**Comment by n4af** [comment]
Best I can tell, by exploiting CWByCAT_Sending,
AUTOSEND with CallTerminate is working...

http://n4af.net
