### ISSUE TITLE
TR4W DX Cluster not automatically connecting to the server if it is not listed in trcluster.dat

### ISSUE THREAD

**Issue by OH6QU** [n4af/TR4W#392]
Following statement in .cfg-file does not open the connection automatically to the telnet server. In order to make it work you need to add the telnet server first to trcluster.dat-file.

;DX-cluster
;----------
TELNET SERVER = ham.connect.fi:7300
CONNECTION AT STARTUP = TRUE
CONNECTION COMMAND = OH6QU

**Comment by ny4i** [comment]
I had a few minutes to look into this issue. It appears that the code in uTelnet.pas (line 345) does this:
```pascal
EnumerateLinesInFile('TRCLUSTER.DAT', EmunTRCLUSTERDAT, False);

i := SendDlgItemMessage(hwnddlg, 102, CB_FINDSTRING, -1, integer(@TelnetServer[1]));    //n4af 4.35.1
if i <> CB_ERR then tCB_SETCURSEL(hwnddlg, 102, i);
```
It appears that rather than set the value of the telnet server to whatever the user places in the config item for telnet server, it builds the drop-down from the file, then does a find.

It appears this should instead try the find and if that does not work, then set it to the actual value and try the connect. Maybe change to something like this:

```pascal
i := SendDlgItemMessage(hwnddlg, 102, CB_FINDSTRING, -1, integer(@TelnetServer[1]));    //n4af 4.35.1
if i <> CB_ERR then 
   begin
   tCB_SETCURSEL(hwnddlg, 102, i);
   end
else
   begin
   //pseudo code
   // Add an entry to the combo box of the value in the config
   // Set the index, I, to the new value?
   end;
```

**Comment by n4af** [comment]
Thanks Tom -

I am leaving for an overnight in Charlottesville Va and will have a look on
return.

If you have a chance, the ctrl-end function to switch focus to the bandmap
does not work when telnet active ?
I would like to see it put the cursor on first entry in the b.m.

Tks, Howie

**Comment by ny4i** [comment]
This has been fixed and is awaiting integration into the main code stream.

**Comment by ny4i** [comment]
This did not make it into the code for some reason. I have to check my local branch and compare to master.

**Comment by ny4i** [comment]
Confirmed as fixed in August 2020 release.
