### ISSUE TITLE
Cannot enter DX Cluster hostname with a dash (-)

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#53]
When typing a host address into DX Cluster window, if the host name has a dash (-), the program intercepts this and wants to change the XMIT frequency. This makes it impossible to enter the host.

**Comment by n4af** [comment]
There are two problems:
1) Dash unfortunately has the same wParam as Alt-N. This can easily be changed to ALT-O and the dash problem will no longer occur. Pls advise if you wish it changed.
2) Entering dash is a problem. 
Key entry is not specific to a window and dash is recognized as a control character. 
Rather than attempt a re-write of wm_KeyDown, under the rare occurance of needing cluster name with a dash, I would suggest just editing TRCLUSTER.DAT and adding the cluster to the list.

**Comment by n4af** [comment]
Dash problem #1 picked up in 4.43.10...

**Comment by ny4i** [comment]
Yes this is still an issue due to the global input handler in uInputQuery.  It would be possible to add some logic to check what control issued the - and if the host box, do not do anything but pass the - to the window but better to push this for consideration if we cannot a better Delphi forms engine in place with Delphi 10.

**Comment by ny4i** [comment]
This now works. I recall I did some work to allow using a dash character. I reworked the way split worked with - as an accelerator if I recall. I tested it and it works. So this will be closed as now working.
