### ISSUE TITLE
Generated ADIF can include <GRIDSQUARE when no grid is in exchange

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#627]
If the domestic consists of two letters and two numbers, for example, CM42,
then the program defines this as GRID and <GRIDSQUARE:4>CM42 is entered in ADIF.

<CALL:6>UA4AAC <BAND:3>40m <QSO_DATE:8>20221204 <TIME_ON:6>093855 <TIME_OFF:6>093855
<RST_SENT:3>599 <RST_RCVD:3>599 <CONTEST_ID:11>GENERAL QSO <MODE:2>CW <SRX_STRING:4>CM42
<STX_STRING:9>599 CM196 <STATE:4>CM42 <GRIDSQUARE:4>CM42 <STX:5>00001 <OPERATOR:5>UR7QM <EOR>

**Comment by n4af** [comment]
The problem resides within function LooksLikeAGrid in Tree.pas
LooksLikeAGrid now checks Active Exchange for a grid exchange, else it returns FALSE, and hence POST will not 
generate GRIDSQUARE.
Fix 4.118.1

**Comment by ny4i** [comment]
﻿Lookslikeagrid is used for WSJT-X in real-time. I think the real issue is if the 4CM42 is returning true because that doesn’t look like a grid. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 4:39 AM, Howie Hoyt ***@***.***> wrote:﻿
The problem resides within function LooksLikeAGrid in Tree.pas
LooksLikeAGrid now checks Active Exchange for a grid exchange, else it returns FALSE, and hence POST will not
generate GRIDSQUARE.
Fix 4.118.1

**Comment by ny4i** [comment]
﻿Lookslikeagrid is used for WSJT-X in real-time. I think the real issue is if the 4CM… is returning true because that doesn’t look like a grid. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 4:39 AM, Howie Hoyt ***@***.***> wrote:﻿
The problem resides within function LooksLikeAGrid in Tree.pas
LooksLikeAGrid now checks Active Exchange for a grid exchange, else it returns FALSE, and hence POST will not
generate GRIDSQUARE.
Fix 4.118.1

**Comment by n4af** [comment]
Hi Tom -

I do not know what 4cm42 is but if you can forward me a fix, we can test it
out...

**Comment by ny4i** [comment]
I guess I’m confused. If the user enters CM42 in the exchange, that is a grid. The 4CM42 was because the ADIF you sent in the bug was missing the <> characters. Was this not a grid?TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 4:36 AM, Howie Hoyt ***@***.***> wrote:﻿
If the domestic consists of two letters and two numbers, for example, CM42,
then the program defines this as GRID and GRIDSQUARE:4CM42 is entered in ADIF.
CALL:6UA4AAC BAND:340m <QSO_DATE:8>20221204 <TIME_ON:6>093855 <TIME_OFF:6>093855
<RST_SENT:3>599 <RST_RCVD:3>599 <CONTEST_ID:11>GENERAL QSO MODE:2CW <SRX_STRING:4>CM42
<STX_STRING:9>599 CM196 STATE:4CM42 GRIDSQUARE:4CM42 STX:500001 OPERATOR:5UR7QM

**Comment by ny4i** [comment]
Was this the real ADIF or a formatting error in GitHub?CALL:6UA4AAC BAND:340m <QSO_DATE:8>20221204 <TIME_ON:6>093855 <TIME_OFF:6>093855<RST_SENT:3>599 <RST_RCVD:3>599 <CONTEST_ID:11>GENERAL QSO MODE:2CW <SRX_STRING:4>CM42<STX_STRING:9>599 CM196 STATE:4CM42 GRIDSQUARE:4CM42 STX:500001 OPERATOR:5UR7QMPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 4:36 AM, Howie Hoyt ***@***.***> wrote:﻿
If the domestic consists of two letters and two numbers, for example, CM42,
then the program defines this as GRID and GRIDSQUARE:4CM42 is entered in ADIF.
CALL:6UA4AAC BAND:340m <QSO_DATE:8>20221204 <TIME_ON:6>093855 <TIME_OFF:6>093855
<RST_SENT:3>599 <RST_RCVD:3>599 <CONTEST_ID:11>GENERAL QSO MODE:2CW <SRX_STRING:4>CM42
<STX_STRING:9>599 CM196 STATE:4CM42 GRIDSQUARE:4CM42 STX:500001 OPERATOR:5UR7QM

**Comment by n4af** [comment]
What is entered in the exchange depends on ACTIVE EXCHANGE. If GRID is not
part of the active exchange then we do not want to
generate <GRIDSQUARE- instead it becomes <QTH

**Comment by ny4i** [comment]
Right but if I’m in General QSO mode and I enter CM42 as a grid, that is indeed a grid and I would think GRIDSQUARE should be in the ADIF. I don’t know why a 40m CW QSO would have a grid but if it does, the only place to export it is in the gridsquare field. But maybe that was a contrived example. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 9:29 AM, Howie Hoyt ***@***.***> wrote:﻿
What is entered in the exchange depends on ACTIVE EXCHANGE. If GRID is not
part of the active exchange then we do not want to
generate <GRIDSQUARE- instead it becomes <QTH

**Comment by n4af** [comment]
Some what nuts, but in ARTIKA-SPRING, as example, CM42 is a QTH.
Perhaps more germane the EXCHANGE RECEIVED parm in the Custom Config is 

EXCHANGE RECEIVED = RST QSO NUMBER AND DOMESTIC QTH

That is why I added code to parse Active Exchange...

**Comment by ny4i** [comment]
I can’t find the rules for that one to check. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by n4af** [comment]
yup. some sorta russian contest but the custom cfg is legit:
MY CALL = UR7QM
MY STATE = CM196
CONTEST = GENERAL QSO
contest title = artika-spring
EXCHANGE RECEIVED = RST QSO NUMBER AND DOMESTIC QTH

**Comment by ny4i** [comment]
Ok. Now I see the problem. Principal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 9:42 AM, Howie Hoyt ***@***.***> wrote:﻿
yup. some sorta russian contest but the custom cfg is legit:
MY CALL = UR7QM
MY STATE = CM196
CONTEST = GENERAL QSO
contest title = artika-spring
EXCHANGE RECEIVED = RST QSO NUMBER AND DOMESTIC QTH

**Comment by ny4i** [comment]
Meaning if a contest is crazy enough to have something that looks like a grid, it’s hard to do anything but what you did. ThanksPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Dec 5, 2022, at 9:42 AM, Howie Hoyt ***@***.***> wrote:﻿
yup. some sorta russian contest but the custom cfg is legit:
MY CALL = UR7QM
MY STATE = CM196
CONTEST = GENERAL QSO
contest title = artika-spring
EXCHANGE RECEIVED = RST QSO NUMBER AND DOMESTIC QTH
